### ISSUE TITLE
Can we make build instead of serve

### ISSUE THREAD

**Issue by goldenratio** [jasmine/jasmine-browser-runner#17]
I would like to generate static javascript files and run those tests myself using nginx. 

I am trying to achieve something like this, https://scriptverse.academy/tutorials/jasmine-spec-browser.html but using modern dev tooling.

Do we have something like,
`jasmine-browser-runner build` ?

**Comment by sgravrock** [comment]
That's not something I want to support in jasmine-browser-runner, in part due to the number of different ways that an incorrect web server configuration could break it. But you could probably build it yourself easily enough by using the `glob` package to build lists of files and then rendering [this template](https://github.com/jasmine/jasmine-browser-runner/blob/main/run.html.ejs) or something similar. I hope that helps.
